# Generated by Django 5.0.6 on 2024-05-16 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('link_id', models.AutoField(primary_key=True, serialize=False)),
                ('relationship_type', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'links',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'subjects',
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('paper_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('authors', models.CharField(max_length=255)),
                ('abstract', models.TextField()),
                ('publication_year', models.DateField()),
                ('keywords', models.CharField(max_length=255)),
                ('cited_references', models.ManyToManyField(related_name='referenced_by', through='graphapi.Link', to='graphapi.paper')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='graphapi.subject')),
            ],
            options={
                'db_table': 'papers',
            },
        ),
        migrations.AddField(
            model_name='link',
            name='paper_id',
            field=models.ForeignKey(db_column='paper_id', on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_links', to='graphapi.paper'),
        ),
        migrations.AddField(
            model_name='link',
            name='related_paper_id',
            field=models.ForeignKey(db_column='related_paper_id', on_delete=django.db.models.deletion.CASCADE, related_name='incoming_links', to='graphapi.paper'),
        ),
    ]
