# Generated by Django 5.0.6 on 2024-05-12 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphapi', '0001_initial'),
    ]

    operations = [
    ]
