# Generated by Django 5.0.6 on 2024-05-20 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphapi', '0002_subject_display_name_subject_overarching_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='overarching_subject',
            field=models.CharField(default='General', max_length=255),
        ),
    ]
