# Generated by Django 5.0.6 on 2024-05-15 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphapi', '0002_auto_20240512_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'subjects',
            },
        ),
        migrations.RenameField(
            model_name='paper',
            old_name='references',
            new_name='cited_references',
        ),
        migrations.RenameField(
            model_name='paper',
            old_name='publication_date',
            new_name='publication_year',
        ),
        migrations.RemoveField(
            model_name='link',
            name='id',
        ),
        migrations.RemoveField(
            model_name='link',
            name='paper',
        ),
        migrations.RemoveField(
            model_name='link',
            name='related_paper',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='citation_count',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='id',
        ),
        migrations.AddField(
            model_name='link',
            name='link_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='link',
            name='paper_id',
            field=models.ForeignKey(db_column='paper_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_links', to='graphapi.paper'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='link',
            name='related_paper_id',
            field=models.ForeignKey(db_column='related_paper_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_links', to='graphapi.paper'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paper',
            name='paper_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='link',
            name='relationship_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='paper',
            name='authors',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='paper',
            name='keywords',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='paper',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterModelTable(
            name='link',
            table='links',
        ),
        migrations.AlterModelTable(
            name='paper',
            table='papers',
        ),
        migrations.AddField(
            model_name='paper',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='graphapi.subject'),
            preserve_default=False,
        ),
    ]
