# Generated by Django 5.0.6 on 2024-05-16 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphapi', '0002_remove_paper_subject_paper_subjects_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='subjects',
        ),
        migrations.AddField(
            model_name='paper',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='graphapi.subject'),
        ),
    ]
