# Generated by Django 5.0.6 on 2024-05-20 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphapi', '0003_alter_subject_overarching_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='paper_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
