# Generated by Django 5.0.6 on 2024-05-27 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphapi', '0005_connectiontype_alter_link_relationship_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectiontype',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
