# Generated by Django 5.0.6 on 2024-06-14 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphapi', '0006_connectiontype_count'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='link',
            unique_together={('paper_id', 'related_paper_id', 'relationship_type')},
        ),
    ]
